use rand::{self, Rng};
use rand_distr::{Normal, Distribution};
use std::{fs::File, io::Write, io::BufWriter, path::Path, time::Instant};

#[derive(Clone)]
struct WeatherStation {
    city: &'static str,
    mean: f64,
}

// data from https://en.wikipedia.org/wiki/List_of_cities_by_average_temperature;
fn get_stations() -> Vec<WeatherStation> {
    vec![
        WeatherStation {city: "Abha", mean: 18.0},
        WeatherStation {city: "Abidjan", mean: 26.0},
        WeatherStation {city: "Abéché", mean: 29.4},
        WeatherStation {city: "Accra", mean: 26.4},
        WeatherStation {city: "Addis Ababa", mean: 16.0},
        WeatherStation {city: "Adelaide", mean: 17.3},
        WeatherStation {city: "Aden", mean: 29.1},
        WeatherStation {city: "Ahvaz", mean: 25.4},
        WeatherStation {city: "Albuquerque", mean: 14.0},
        WeatherStation {city: "Alexandra", mean: 11.0},
        WeatherStation {city: "Alexandria", mean: 20.0},
        WeatherStation {city: "Algiers", mean: 18.2},
        WeatherStation {city: "Alice Springs", mean: 21.0},
        WeatherStation {city: "Almaty", mean: 10.0},
        WeatherStation {city: "Amsterdam", mean: 10.2},
        WeatherStation {city: "Anadyr", mean: -6.9},
        WeatherStation {city: "Anchorage", mean: 2.8},
        WeatherStation {city: "Andorra la Vella", mean: 9.8},
        WeatherStation {city: "Ankara", mean: 12.0},
        WeatherStation {city: "Antananarivo", mean: 17.9},
        WeatherStation {city: "Antsiranana", mean: 25.2},
        WeatherStation {city: "Arkhangelsk", mean: 1.3},
        WeatherStation {city: "Ashgabat", mean: 17.1},
        WeatherStation {city: "Asmara", mean: 15.6},
        WeatherStation {city: "Assab", mean: 30.5},
        WeatherStation {city: "Astana", mean: 3.5},
        WeatherStation {city: "Athens", mean: 19.2},
        WeatherStation {city: "Atlanta", mean: 17.0},
        WeatherStation {city: "Auckland", mean: 15.2},
        WeatherStation {city: "Austin", mean: 20.7},
        WeatherStation {city: "Baghdad", mean: 22.77},
        WeatherStation {city: "Baguio", mean: 19.5},
        WeatherStation {city: "Baku", mean: 15.1},
        WeatherStation {city: "Baltimore", mean: 13.1},
        WeatherStation {city: "Bamako", mean: 27.8},
        WeatherStation {city: "Bangkok", mean: 28.6},
        WeatherStation {city: "Bangui", mean: 26.0},
        WeatherStation {city: "Banjul", mean: 26.0},
        WeatherStation {city: "Barcelona", mean: 18.2},
        WeatherStation {city: "Bata", mean: 25.1},
        WeatherStation {city: "Batumi", mean: 14.0},
        WeatherStation {city: "Beijing", mean: 12.9},
        WeatherStation {city: "Beirut", mean: 20.9},
        WeatherStation {city: "Belgrade", mean: 12.5},
        WeatherStation {city: "Belize City", mean: 26.7},
        WeatherStation {city: "Benghazi", mean: 19.9},
        WeatherStation {city: "Bergen", mean: 7.7},
        WeatherStation {city: "Berlin", mean: 10.3},
        WeatherStation {city: "Bilbao", mean: 14.7},
        WeatherStation {city: "Birao", mean: 26.5},
        WeatherStation {city: "Bishkek", mean: 11.3},
        WeatherStation {city: "Bissau", mean: 27.0},
        WeatherStation {city: "Blantyre", mean: 22.2},
        WeatherStation {city: "Bloemfontein", mean: 15.6},
        WeatherStation {city: "Boise", mean: 11.4},
        WeatherStation {city: "Bordeaux", mean: 14.2},
        WeatherStation {city: "Bosaso", mean: 30.0},
        WeatherStation {city: "Boston", mean: 10.9},
        WeatherStation {city: "Bouaké", mean: 26.0},
        WeatherStation {city: "Bratislava", mean: 10.5},
        WeatherStation {city: "Brazzaville", mean: 25.0},
        WeatherStation {city: "Bridgetown", mean: 27.0},
        WeatherStation {city: "Brisbane", mean: 21.4},
        WeatherStation {city: "Brussels", mean: 10.5},
        WeatherStation {city: "Bucharest", mean: 10.8},
        WeatherStation {city: "Budapest", mean: 11.3},
        WeatherStation {city: "Bujumbura", mean: 23.8},
        WeatherStation {city: "Bulawayo", mean: 18.9},
        WeatherStation {city: "Burnie", mean: 13.1},
        WeatherStation {city: "Busan", mean: 15.0},
        WeatherStation {city: "Cabo San Lucas", mean: 23.9},
        WeatherStation {city: "Cairns", mean: 25.0},
        WeatherStation {city: "Cairo", mean: 21.4},
        WeatherStation {city: "Calgary", mean: 4.4},
        WeatherStation {city: "Canberra", mean: 13.1},
        WeatherStation {city: "Cape Town", mean: 16.2},
        WeatherStation {city: "Changsha", mean: 17.4},
        WeatherStation {city: "Charlotte", mean: 16.1},
        WeatherStation {city: "Chiang Mai", mean: 25.8},
        WeatherStation {city: "Chicago", mean: 9.8},
        WeatherStation {city: "Chihuahua", mean: 18.6},
        WeatherStation {city: "Chișinău", mean: 10.2},
        WeatherStation {city: "Chittagong", mean: 25.9},
        WeatherStation {city: "Chongqing", mean: 18.6},
        WeatherStation {city: "Christchurch", mean: 12.2},
        WeatherStation {city: "City of San Marino", mean: 11.8},
        WeatherStation {city: "Colombo", mean: 27.4},
        WeatherStation {city: "Columbus", mean: 11.7},
        WeatherStation {city: "Conakry", mean: 26.4},
        WeatherStation {city: "Copenhagen", mean: 9.1},
        WeatherStation {city: "Cotonou", mean: 27.2},
        WeatherStation {city: "Cracow", mean: 9.3},
        WeatherStation {city: "Da Lat", mean: 17.9},
        WeatherStation {city: "Da Nang", mean: 25.8},
        WeatherStation {city: "Dakar", mean: 24.0},
        WeatherStation {city: "Dallas", mean: 19.0},
        WeatherStation {city: "Damascus", mean: 17.0},
        WeatherStation {city: "Dampier", mean: 26.4},
        WeatherStation {city: "Dar es Salaam", mean: 25.8},
        WeatherStation {city: "Darwin", mean: 27.6},
        WeatherStation {city: "Denpasar", mean: 23.7},
        WeatherStation {city: "Denver", mean: 10.4},
        WeatherStation {city: "Detroit", mean: 10.0},
        WeatherStation {city: "Dhaka", mean: 25.9},
        WeatherStation {city: "Dikson", mean: -11.1},
        WeatherStation {city: "Dili", mean: 26.6},
        WeatherStation {city: "Djibouti", mean: 29.9},
        WeatherStation {city: "Dodoma", mean: 22.7},
        WeatherStation {city: "Dolisie", mean: 24.0},
        WeatherStation {city: "Douala", mean: 26.7},
        WeatherStation {city: "Dubai", mean: 26.9},
        WeatherStation {city: "Dublin", mean: 9.8},
        WeatherStation {city: "Dunedin", mean: 11.1},
        WeatherStation {city: "Durban", mean: 20.6},
        WeatherStation {city: "Dushanbe", mean: 14.7},
        WeatherStation {city: "Edinburgh", mean: 9.3},
        WeatherStation {city: "Edmonton", mean: 4.2},
        WeatherStation {city: "El Paso", mean: 18.1},
        WeatherStation {city: "Entebbe", mean: 21.0},
        WeatherStation {city: "Erbil", mean: 19.5},
        WeatherStation {city: "Erzurum", mean: 5.1},
        WeatherStation {city: "Fairbanks", mean: -2.3},
        WeatherStation {city: "Fianarantsoa", mean: 17.9},
        WeatherStation {city: "Flores,  Petén", mean: 26.4},
        WeatherStation {city: "Frankfurt", mean: 10.6},
        WeatherStation {city: "Fresno", mean: 17.9},
        WeatherStation {city: "Fukuoka", mean: 17.0},
        WeatherStation {city: "Gabès", mean: 19.5},
        WeatherStation {city: "Gaborone", mean: 21.0},
        WeatherStation {city: "Gagnoa", mean: 26.0},
        WeatherStation {city: "Gangtok", mean: 15.2},
        WeatherStation {city: "Garissa", mean: 29.3},
        WeatherStation {city: "Garoua", mean: 28.3},
        WeatherStation {city: "George Town", mean: 27.9},
        WeatherStation {city: "Ghanzi", mean: 21.4},
        WeatherStation {city: "Gjoa Haven", mean: -14.4},
        WeatherStation {city: "Guadalajara", mean: 20.9},
        WeatherStation {city: "Guangzhou", mean: 22.4},
        WeatherStation {city: "Guatemala City", mean: 20.4},
        WeatherStation {city: "Halifax", mean: 7.5},
        WeatherStation {city: "Hamburg", mean: 9.7},
        WeatherStation {city: "Hamilton", mean: 13.8},
        WeatherStation {city: "Hanga Roa", mean: 20.5},
        WeatherStation {city: "Hanoi", mean: 23.6},
        WeatherStation {city: "Harare", mean: 18.4},
        WeatherStation {city: "Harbin", mean: 5.0},
        WeatherStation {city: "Hargeisa", mean: 21.7},
        WeatherStation {city: "Hat Yai", mean: 27.0},
        WeatherStation {city: "Havana", mean: 25.2},
        WeatherStation {city: "Helsinki", mean: 5.9},
        WeatherStation {city: "Heraklion", mean: 18.9},
        WeatherStation {city: "Hiroshima", mean: 16.3},
        WeatherStation {city: "Ho Chi Minh City", mean: 27.4},
        WeatherStation {city: "Hobart", mean: 12.7},
        WeatherStation {city: "Hong Kong", mean: 23.3},
        WeatherStation {city: "Honiara", mean: 26.5},
        WeatherStation {city: "Honolulu", mean: 25.4},
        WeatherStation {city: "Houston", mean: 20.8},
        WeatherStation {city: "Ifrane", mean: 11.4},
        WeatherStation {city: "Indianapolis", mean: 11.8},
        WeatherStation {city: "Iqaluit", mean: -9.3},
        WeatherStation {city: "Irkutsk", mean: 1.0},
        WeatherStation {city: "Istanbul", mean: 13.9},
        WeatherStation {city: "İzmir", mean: 17.9},
        WeatherStation {city: "Jacksonville", mean: 20.3},
        WeatherStation {city: "Jakarta", mean: 26.7},
        WeatherStation {city: "Jayapura", mean: 27.0},
        WeatherStation {city: "Jerusalem", mean: 18.3},
        WeatherStation {city: "Johannesburg", mean: 15.5},
        WeatherStation {city: "Jos", mean: 22.8},
        WeatherStation {city: "Juba", mean: 27.8},
        WeatherStation {city: "Kabul", mean: 12.1},
        WeatherStation {city: "Kampala", mean: 20.0},
        WeatherStation {city: "Kandi", mean: 27.7},
        WeatherStation {city: "Kankan", mean: 26.5},
        WeatherStation {city: "Kano", mean: 26.4},
        WeatherStation {city: "Kansas City", mean: 12.5},
        WeatherStation {city: "Karachi", mean: 26.0},
        WeatherStation {city: "Karonga", mean: 24.4},
        WeatherStation {city: "Kathmandu", mean: 18.3},
        WeatherStation {city: "Khartoum", mean: 29.9},
        WeatherStation {city: "Kingston", mean: 27.4},
        WeatherStation {city: "Kinshasa", mean: 25.3},
        WeatherStation {city: "Kolkata", mean: 26.7},
        WeatherStation {city: "Kuala Lumpur", mean: 27.3},
        WeatherStation {city: "Kumasi", mean: 26.0},
        WeatherStation {city: "Kunming", mean: 15.7},
        WeatherStation {city: "Kuopio", mean: 3.4},
        WeatherStation {city: "Kuwait City", mean: 25.7},
        WeatherStation {city: "Kyiv", mean: 8.4},
        WeatherStation {city: "Kyoto", mean: 15.8},
        WeatherStation {city: "La Ceiba", mean: 26.2},
        WeatherStation {city: "La Paz", mean: 23.7},
        WeatherStation {city: "Lagos", mean: 26.8},
        WeatherStation {city: "Lahore", mean: 24.3},
        WeatherStation {city: "Lake Havasu City", mean: 23.7},
        WeatherStation {city: "Lake Tekapo", mean: 8.7},
        WeatherStation {city: "Las Palmas de Gran Canaria", mean: 21.2},
        WeatherStation {city: "Las Vegas", mean: 20.3},
        WeatherStation {city: "Launceston", mean: 13.1},
        WeatherStation {city: "Lhasa", mean: 7.6},
        WeatherStation {city: "Libreville", mean: 25.9},
        WeatherStation {city: "Lisbon", mean: 17.5},
        WeatherStation {city: "Livingstone", mean: 21.8},
        WeatherStation {city: "Ljubljana", mean: 10.9},
        WeatherStation {city: "Lodwar", mean: 29.3},
        WeatherStation {city: "Lomé", mean: 26.9},
        WeatherStation {city: "London", mean: 11.3},
        WeatherStation {city: "Los Angeles", mean: 18.6},
        WeatherStation {city: "Louisville", mean: 13.9},
        WeatherStation {city: "Luanda", mean: 25.8},
        WeatherStation {city: "Lubumbashi", mean: 20.8},
        WeatherStation {city: "Lusaka", mean: 19.9},
        WeatherStation {city: "Luxembourg City", mean: 9.3},
        WeatherStation {city: "Lviv", mean: 7.8},
        WeatherStation {city: "Lyon", mean: 12.5},
        WeatherStation {city: "Madrid", mean: 15.0},
        WeatherStation {city: "Mahajanga", mean: 26.3},
        WeatherStation {city: "Makassar", mean: 26.7},
        WeatherStation {city: "Makurdi", mean: 26.0},
        WeatherStation {city: "Malabo", mean: 26.3},
        WeatherStation {city: "Malé", mean: 28.0},
        WeatherStation {city: "Managua", mean: 27.3},
        WeatherStation {city: "Manama", mean: 26.5},
        WeatherStation {city: "Mandalay", mean: 28.0},
        WeatherStation {city: "Mango", mean: 28.1},
        WeatherStation {city: "Manila", mean: 28.4},
        WeatherStation {city: "Maputo", mean: 22.8},
        WeatherStation {city: "Marrakesh", mean: 19.6},
        WeatherStation {city: "Marseille", mean: 15.8},
        WeatherStation {city: "Maun", mean: 22.4},
        WeatherStation {city: "Medan", mean: 26.5},
        WeatherStation {city: "Mek'ele", mean: 22.7},
        WeatherStation {city: "Melbourne", mean: 15.1},
        WeatherStation {city: "Memphis", mean: 17.2},
        WeatherStation {city: "Mexicali", mean: 23.1},
        WeatherStation {city: "Mexico City", mean: 17.5},
        WeatherStation {city: "Miami", mean: 24.9},
        WeatherStation {city: "Milan", mean: 13.0},
        WeatherStation {city: "Milwaukee", mean: 8.9},
        WeatherStation {city: "Minneapolis", mean: 7.8},
        WeatherStation {city: "Minsk", mean: 6.7},
        WeatherStation {city: "Mogadishu", mean: 27.1},
        WeatherStation {city: "Mombasa", mean: 26.3},
        WeatherStation {city: "Monaco", mean: 16.4},
        WeatherStation {city: "Moncton", mean: 6.1},
        WeatherStation {city: "Monterrey", mean: 22.3},
        WeatherStation {city: "Montreal", mean: 6.8},
        WeatherStation {city: "Moscow", mean: 5.8},
        WeatherStation {city: "Mumbai", mean: 27.1},
        WeatherStation {city: "Murmansk", mean: 0.6},
        WeatherStation {city: "Muscat", mean: 28.0},
        WeatherStation {city: "Mzuzu", mean: 17.7},
        WeatherStation {city: "N'Djamena", mean: 28.3},
        WeatherStation {city: "Naha", mean: 23.1},
        WeatherStation {city: "Nairobi", mean: 17.8},
        WeatherStation {city: "Nakhon Ratchasima", mean: 27.3},
        WeatherStation {city: "Napier", mean: 14.6},
        WeatherStation {city: "Napoli", mean: 15.9},
        WeatherStation {city: "Nashville", mean: 15.4},
        WeatherStation {city: "Nassau", mean: 24.6},
        WeatherStation {city: "Ndola", mean: 20.3},
        WeatherStation {city: "New Delhi", mean: 25.0},
        WeatherStation {city: "New Orleans", mean: 20.7},
        WeatherStation {city: "New York City", mean: 12.9},
        WeatherStation {city: "Ngaoundéré", mean: 22.0},
        WeatherStation {city: "Niamey", mean: 29.3},
        WeatherStation {city: "Nicosia", mean: 19.7},
        WeatherStation {city: "Niigata", mean: 13.9},
        WeatherStation {city: "Nouadhibou", mean: 21.3},
        WeatherStation {city: "Nouakchott", mean: 25.7},
        WeatherStation {city: "Novosibirsk", mean: 1.7},
        WeatherStation {city: "Nuuk", mean: -1.4},
        WeatherStation {city: "Odesa", mean: 10.7},
        WeatherStation {city: "Odienné", mean: 26.0},
        WeatherStation {city: "Oklahoma City", mean: 15.9},
        WeatherStation {city: "Omaha", mean: 10.6},
        WeatherStation {city: "Oranjestad", mean: 28.1},
        WeatherStation {city: "Oslo", mean: 5.7},
        WeatherStation {city: "Ottawa", mean: 6.6},
        WeatherStation {city: "Ouagadougou", mean: 28.3},
        WeatherStation {city: "Ouahigouya", mean: 28.6},
        WeatherStation {city: "Ouarzazate", mean: 18.9},
        WeatherStation {city: "Oulu", mean: 2.7},
        WeatherStation {city: "Palembang", mean: 27.3},
        WeatherStation {city: "Palermo", mean: 18.5},
        WeatherStation {city: "Palm Springs", mean: 24.5},
        WeatherStation {city: "Palmerston North", mean: 13.2},
        WeatherStation {city: "Panama City", mean: 28.0},
        WeatherStation {city: "Parakou", mean: 26.8},
        WeatherStation {city: "Paris", mean: 12.3},
        WeatherStation {city: "Perth", mean: 18.7},
        WeatherStation {city: "Petropavlovsk-Kamchatsky", mean: 1.9},
        WeatherStation {city: "Philadelphia", mean: 13.2},
        WeatherStation {city: "Phnom Penh", mean: 28.3},
        WeatherStation {city: "Phoenix", mean: 23.9},
        WeatherStation {city: "Pittsburgh", mean: 10.8},
        WeatherStation {city: "Podgorica", mean: 15.3},
        WeatherStation {city: "Pointe-Noire", mean: 26.1},
        WeatherStation {city: "Pontianak", mean: 27.7},
        WeatherStation {city: "Port Moresby", mean: 26.9},
        WeatherStation {city: "Port Sudan", mean: 28.4},
        WeatherStation {city: "Port Vila", mean: 24.3},
        WeatherStation {city: "Port-Gentil", mean: 26.0},
        WeatherStation {city: "Portland {OR}", mean: 12.4},
        WeatherStation {city: "Porto", mean: 15.7},
        WeatherStation {city: "Prague", mean: 8.4},
        WeatherStation {city: "Praia", mean: 24.4},
        WeatherStation {city: "Pretoria", mean: 18.2},
        WeatherStation {city: "Pyongyang", mean: 10.8},
        WeatherStation {city: "Rabat", mean: 17.2},
        WeatherStation {city: "Rangpur", mean: 24.4},
        WeatherStation {city: "Reggane", mean: 28.3},
        WeatherStation {city: "Reykjavík", mean: 4.3},
        WeatherStation {city: "Riga", mean: 6.2},
        WeatherStation {city: "Riyadh", mean: 26.0},
        WeatherStation {city: "Rome", mean: 15.2},
        WeatherStation {city: "Roseau", mean: 26.2},
        WeatherStation {city: "Rostov-on-Don", mean: 9.9},
        WeatherStation {city: "Sacramento", mean: 16.3},
        WeatherStation {city: "Saint Petersburg", mean: 5.8},
        WeatherStation {city: "Saint-Pierre", mean: 5.7},
        WeatherStation {city: "Salt Lake City", mean: 11.6},
        WeatherStation {city: "San Antonio", mean: 20.8},
        WeatherStation {city: "San Diego", mean: 17.8},
        WeatherStation {city: "San Francisco", mean: 14.6},
        WeatherStation {city: "San Jose", mean: 16.4},
        WeatherStation {city: "San José", mean: 22.6},
        WeatherStation {city: "San Juan", mean: 27.2},
        WeatherStation {city: "San Salvador", mean: 23.1},
        WeatherStation {city: "Sana'a", mean: 20.0},
        WeatherStation {city: "Santo Domingo", mean: 25.9},
        WeatherStation {city: "Sapporo", mean: 8.9},
        WeatherStation {city: "Sarajevo", mean: 10.1},
        WeatherStation {city: "Saskatoon", mean: 3.3},
        WeatherStation {city: "Seattle", mean: 11.3},
        WeatherStation {city: "Ségou", mean: 28.0},
        WeatherStation {city: "Seoul", mean: 12.5},
        WeatherStation {city: "Seville", mean: 19.2},
        WeatherStation {city: "Shanghai", mean: 16.7},
        WeatherStation {city: "Singapore", mean: 27.0},
        WeatherStation {city: "Skopje", mean: 12.4},
        WeatherStation {city: "Sochi", mean: 14.2},
        WeatherStation {city: "Sofia", mean: 10.6},
        WeatherStation {city: "Sokoto", mean: 28.0},
        WeatherStation {city: "Split", mean: 16.1},
        WeatherStation {city: "St. John's", mean: 5.0},
        WeatherStation {city: "St. Louis", mean: 13.9},
        WeatherStation {city: "Stockholm", mean: 6.6},
        WeatherStation {city: "Surabaya", mean: 27.1},
        WeatherStation {city: "Suva", mean: 25.6},
        WeatherStation {city: "Suwałki", mean: 7.2},
        WeatherStation {city: "Sydney", mean: 17.7},
        WeatherStation {city: "Tabora", mean: 23.0},
        WeatherStation {city: "Tabriz", mean: 12.6},
        WeatherStation {city: "Taipei", mean: 23.0},
        WeatherStation {city: "Tallinn", mean: 6.4},
        WeatherStation {city: "Tamale", mean: 27.9},
        WeatherStation {city: "Tamanrasset", mean: 21.7},
        WeatherStation {city: "Tampa", mean: 22.9},
        WeatherStation {city: "Tashkent", mean: 14.8},
        WeatherStation {city: "Tauranga", mean: 14.8},
        WeatherStation {city: "Tbilisi", mean: 12.9},
        WeatherStation {city: "Tegucigalpa", mean: 21.7},
        WeatherStation {city: "Tehran", mean: 17.0},
        WeatherStation {city: "Tel Aviv", mean: 20.0},
        WeatherStation {city: "Thessaloniki", mean: 16.0},
        WeatherStation {city: "Thiès", mean: 24.0},
        WeatherStation {city: "Tijuana", mean: 17.8},
        WeatherStation {city: "Timbuktu", mean: 28.0},
        WeatherStation {city: "Tirana", mean: 15.2},
        WeatherStation {city: "Toamasina", mean: 23.4},
        WeatherStation {city: "Tokyo", mean: 15.4},
        WeatherStation {city: "Toliara", mean: 24.1},
        WeatherStation {city: "Toluca", mean: 12.4},
        WeatherStation {city: "Toronto", mean: 9.4},
        WeatherStation {city: "Tripoli", mean: 20.0},
        WeatherStation {city: "Tromsø", mean: 2.9},
        WeatherStation {city: "Tucson", mean: 20.9},
        WeatherStation {city: "Tunis", mean: 18.4},
        WeatherStation {city: "Ulaanbaatar", mean: -0.4},
        WeatherStation {city: "Upington", mean: 20.4},
        WeatherStation {city: "Ürümqi", mean: 7.4},
        WeatherStation {city: "Vaduz", mean: 10.1},
        WeatherStation {city: "Valencia", mean: 18.3},
        WeatherStation {city: "Valletta", mean: 18.8},
        WeatherStation {city: "Vancouver", mean: 10.4},
        WeatherStation {city: "Veracruz", mean: 25.4},
        WeatherStation {city: "Vienna", mean: 10.4},
        WeatherStation {city: "Vientiane", mean: 25.9},
        WeatherStation {city: "Villahermosa", mean: 27.1},
        WeatherStation {city: "Vilnius", mean: 6.0},
        WeatherStation {city: "Virginia Beach", mean: 15.8},
        WeatherStation {city: "Vladivostok", mean: 4.9},
        WeatherStation {city: "Warsaw", mean: 8.5},
        WeatherStation {city: "Washington, D.C.", mean: 14.6},
        WeatherStation {city: "Wau", mean: 27.8},
        WeatherStation {city: "Wellington", mean: 12.9},
        WeatherStation {city: "Whitehorse", mean: -0.1},
        WeatherStation {city: "Wichita", mean: 13.9},
        WeatherStation {city: "Willemstad", mean: 28.0},
        WeatherStation {city: "Winnipeg", mean: 3.0},
        WeatherStation {city: "Wrocław", mean: 9.6},
        WeatherStation {city: "Xi'an", mean: 14.1},
        WeatherStation {city: "Yakutsk", mean: -8.8},
        WeatherStation {city: "Yangon", mean: 27.5},
        WeatherStation {city: "Yaoundé", mean: 23.8},
        WeatherStation {city: "Yellowknife", mean: -4.3},
        WeatherStation {city: "Yerevan", mean: 12.4},
        WeatherStation {city: "Yinchuan", mean: 9.0},
        WeatherStation {city: "Zagreb", mean: 10.7},
        WeatherStation {city: "Zanzibar City", mean: 26.0},
        WeatherStation {city: "Zürich", mean: 9.3}
    ]
}

fn rand_nd(mean: f64) -> f64 {
    let normal = Normal::new(mean, 10.0).unwrap();
    let v = normal.sample(&mut rand::thread_rng());
    (v.floor() * 10.0) / 10.0
}

pub fn sample(path: &Path, size: u64) {
    let start = Instant::now();

    let file = File::create(path).unwrap();
    let mut writer = BufWriter::new(file);
    let stations: Vec<WeatherStation> = get_stations();
    let numb_stations = stations.len();
    let mut rng = rand::thread_rng();

    for i in 0..size {
        if i > 0 && i % 50_000_000 == 0 {
            println!("Wrote {:?}, measurements in {:?} ms", i, start.elapsed());
        }
        let c =  rng.gen::<usize>() % numb_stations;
        let line = format!("{:?};{:?}\n", stations[c].city, rand_nd(stations[c].mean));
        let _ = writer.write(line.as_bytes());
    }

    println!("Created file with {:?} measurements in {:?} ms", size, start.elapsed().as_millis());
}
